#!/bin/sh


if [ ! -f "/usr/portage/header.txt" ]
then
	echo "/usr/portage doesn't appear to be mounted."
	exit 1
fi

STAMP="$(date +%F)_$(date +%T)_portage"

DESTINATION="/data/backup/$(hostname)/${STAMP}/"

if [ -d "$DESTINATION" ]
then
	echo "Destination $DESTINATION already exists."
	exit 1
fi

for DELAY in $(seq 1 5 | sort -r)
do
	echo "Backup up to ${DESTINATION} in ${DELAY}.."
	sleep 1
done

STAGING="${DESTINATION}staging"

mkdir -p "$STAGING"

TARGETS="
/usr/portage
"
echo "Staging files.."

for TARGET in $TARGETS
do
	echo "Staging target ${TARGET}.."
	rsync -aAX \
		-H \
		--info=progress2 \
		--numeric-ids \
		"$TARGET" "$STAGING"
done

echo "Creating archive ${ARCHIVE}.."

ARCHIVE="backup.tar.gz"

cd "$STAGING"

tar cvzf "../$ARCHIVE" .

cd -

echo "Cleaning up.."

rm -rf "$STAGING"

echo " All done."
