#!/bin/sh

LOG_FILE="/var/log/$(basename $0)_${1}_${2}.log"

if [ -f "$LOG_FILE" ]
then
        rm "$LOG_FILE"
fi

function log()
{
        MESSAGE="[$(date)] => [$0]: $*"
        echo "$MESSAGE"
        echo "$MESSAGE" >> "$LOG_FILE"
}


dofans=false

case "$1 $2" in
	"post suspend"|"post hibernate"|"post hybrid-sleep")
		dofans=true
	;;
esac

if [ "$dofans" = true ]
then
	log "Restarting nct6775_fancontrol.."
	systemctl restart nct6775_fancontrol.service
fi
