#!/bin/sh

LOG_FILE="/var/log/$(basename $0)_${1}_${2}.log"

if [ -f "$LOG_FILE" ]
then
        rm "$LOG_FILE"
fi

function log()
{
        MESSAGE="[$(date)] => [$0]: $*"
        echo "$MESSAGE"
        echo "$MESSAGE" >> "$LOG_FILE"
}


action_none="none"
action_load="load"
action_unload="unload"

action="${action_none}"

log "Event: $1 $2"

case "$1 $2" in
	"pre suspend"|"pre hibernate"|"pre hybrid-sleep")
		action="${action_unload}"
	;;
        "post suspend"|"post hibernate"|"post hybrid-sleep")
                action="${action_load}"
        ;;
	*)
		log "Event was not handled."
		exit 0
esac

log "Event was handled. Action: ${action}."

config_dir="/etc/pm/config.d"

if [ -d "${config_dir}" ]
then
	for file in ${config_dir}/*
	do
		log "Loading config file ${file}."
		source "$file"
	done
else
	log "Config dir ${config_dir} does not exist."
	exit 0
fi

if [ -z "$SUSPEND_MODULES" ]
then
	log "No modules were configured."
	exit 0
fi

log "Modules: ${SUSPEND_MODULES}."

function do_unload()
{
	for module in ${SUSPEND_MODULES}
	do
		loaded=$(lsmod | grep "$module")
		if [ -z "$loaded" ]
		then
			log "Module ${module} is not loaded."
			continue
		fi
		log "Unloading module ${module}."
		rmmod "$module"
		if [ ! "$?" = "0" ]
		then
			log "Failed to unload module ${module}."
		fi
	done
}

function do_load()
{
        for module in ${SUSPEND_MODULES}
        do
                loaded=$(lsmod | grep "$module")
                if [ ! -z "$loaded" ]
                then
                        log "Module ${module} is already loaded."
                        continue
                fi
                log "Loading module ${module}."
                modprobe "$module"
                if [ ! "$?" = "0" ]
                then
                        log "Failed to load module ${module}."
                fi
        done

}

case "${action}" in
	"${action_unload}")
		do_unload
	;;
	"${action_load}")
		do_load
	;;
esac
